version: '3'

networks:
  traefik-network:
    external: true

services:
  mirotalk:
    image: mirotalk/p2p:latest
    container_name: mirotalkp2p
    hostname: mirotalkp2p
    volumes:
        - .env:/src/.env:ro
        # These volumes are not mandatory, uncomment if you want to use it
        # - ./app/:/src/app/:ro
        # - ./public/:/src/public/:ro
    restart: unless-stopped
    # ports:
    #     - '${PORT}:${PORT}'
  # Uncomment below, remove "ports:" section above and configure labels as
  # needed for LetsEncrypt TLS certificates with Traefik.
  # See https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
    # expose:
    #   - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mirotalkp2p.rule=Host(`${MICROTALK_P2P_HOSTNAME}`)"
      - "traefik.http.routers.mirotalkp2p.entrypoints=websecure"
      - "traefik.http.routers.mirotalkp2p.tls.certresolver=letsencrypt"
      - "traefik.http.services.mirotalkp2p.loadbalancer.server.port=${PORT}"
      - "traefik.docker.network=traefik-network"
    networks:
      - traefik-network