version: '3.5'

services:
  rancher:
    image: rancher/rancher:latest
    hostname: rancher.c1tech.group 
    restart: always
    # ports:
    # - "80:80/tcp"
    # - "443:443/tcp"
    volumes:
    - "rancher-data:/var/lib/rancher"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rancher.rule=Host(`rancher.c1tech.group`)"
      - "traefik.http.services.rancher.loadbalancer.server.port=80"
      - "traefik.http.routers.rancher.entrypoints=secure"
      - "traefik.http.routers.rancher.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"
    volumes:
    privileged: true
    networks:
      - web
networks:
  web:
    external: true