networks:
  openldap-network:
    external: true
  traefik-network:
    external: true

volumes:
  openldap-data:
    external: true
services:
  openldap:
    container_name: openldap
    image: ${OPENLDAP_IMAGE_TAG}
    hostname: ${OPENLDAP_HOSTNAME}
    restart: unless-stopped
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      # https://hub.docker.com/r/bitnami/openldap/  
      - LDAP_ROOT=${OPENLDAP_ROOT}
      - LDAP_ADMIN_DN=${OPENLDAP_ADMIN_DN}
      - LDAP_ADMIN_USERNAME=${OPENLDAP_ADMIN_USERNAME}
      - LDAP_ADMIN_PASSWORD=${OPENLDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_ADMIN_ENABLED = ${OPENLDAP_CONFIG_ADMIN_ENABLED}
      - LDAP_CONFIG_ADMIN_USERNAME = ${OPENLDAP_CONFIG_ADMIN_USERNAME}
      - LDAP_CONFIG_ADMIN_PASSWORD=${OPENLDAP_CONFIG_ADMIN_PASSWORD}
      - LDAP_USERS=${OPENLDAP_USERS}
      - LDAP_PASSWORDS=${OPENLDAP_PASSWORDS}
      - LDAP_PORT_NUMBER=${OPENLDAP_PORT_NUMBER}
      - LDAP_LDAPS_PORT_NUMBER=${OPENLDAP_LDAPS_PORT_NUMBER}
      - LDAP_ENABLE_TLS=${OPENLDAP_ENABLE_TLS}
      - LDAP_REQUIRE_TLS=${OPENLDAP_REQUIRE_TLS}
      - LDAP_TLS_DH_PARAMS_FILE=${OPENLDAP_TLS_DH_PARAMS_FILE}
      - LDAP_TLS_CERT_FILE=${OPENLDAP_TLS_CERT_FILE}
      - LDAP_TLS_KEY_FILE=${OPENLDAP_TLS_KEY_FILE}
      - LDAP_TLS_CA_FILE=${OPENLDAP_TLS_CA_FILE}
      - LDAP_URI=${OPENLDAP_URI}
      - LDAP_ALLOW_ANON_BINDING=${OPENLDAP_ALLOW_ANON_BINDING}
      # EXTENDED BITNAMI LDAP ENV..
      - LDAP_HASH_PASSWORD=CRYPT
    volumes:
      - /etc/letsencrypt/live/${OPENLDAP_HOSTNAME}/cert.pem:/opt/bitnami/openldap/certs/cert.pem
      - /etc/letsencrypt/live/${OPENLDAP_HOSTNAME}/privkey.pem:/opt/bitnami/openldap/certs/privkey.pem
      - /etc/letsencrypt/live/${OPENLDAP_HOSTNAME}/chain.pem:/opt/bitnami/openldap/certs/chain.pem
      - /etc/letsencrypt/live/${OPENLDAP_HOSTNAME}/dhparam.pem:/opt/bitnami/openldap/certs/dhparam.pem
      - openldap-data:/bitnami/openldap/
    networks:
      - openldap-network
      - traefik-network

  phpldapadmin:
    container_name: openldap-phpldapadmin
    image: osixia/phpldapadmin:0.9.0
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: |
        #PYTHON2BASH:[
          {'openldap': [
            {'server': [
              {'host': 'ldap://openldap:${OPENLDAP_PORT_NUMBER}'}
            ]},
            {'login': [{'bind_id': '${OPENLDAP_ADMIN_DN}'}]}
          ]}
        ]
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.phpldapadmin.rule=Host(`${OPENLDAP_PHPLDAPADMIN_HOSTNAME}`)"
    - "traefik.http.services.phpldapadmin.loadbalancer.server.port=80"
    - "traefik.http.routers.phpldapadmin.entrypoints=websecure"
    - "traefik.http.routers.phpldapadmin.tls.certresolver=letsencrypt"
    - "traefik.docker.network=traefik-network"
    depends_on:
      - openldap
    networks:
      - openldap-network
      - traefik-network