version: "3.5"
services:
  openldap:
    container_name: "openldap"
    image: docker.io/bitnami/openldap:2.6
    hostname: ldap.c1tech.group
    ports:
      - '389:389'
      - '636:636'
    environment:
      - LDAP_PORT_NUMBER=389
      - LDAP_ROOT=dc=c1tech,dc=co
      - LDAP_ADMIN_DN=cn=admin,dc=c1tech,dc=co
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=OpenLDAPpass.24
      - LDAP_CONFIG_ADMIN_PASSWORD=adminconfig
      - LDAP_CONFIG_ADMIN_PASSWORD=OpenLDAPconfig.24
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_LDAPS_PORT_NUMBER=636
      - LDAP_ENABLE_TLS=yes
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/cert.pem
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/privkey.pem
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/chain.pem
    volumes:
      - /home/c1tech/dev/openldap/certs:/opt/bitnami/openldap/certs
      - openldap_data:/bitnami/openldap/
      # - /data2/openldap:/bitnami/openldap/
    networks:
      - web
volumes:
  openldap_data:
    driver: local
  web:
    external: true