version: '3.7'

x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  monitoring-network:
    external: true
  traefik-network:
    external: true

volumes:
  prometheus-data:
    external: true
  grafana-data:
    external: true
  grafana-settings:
    external: true
  loki-data:
    external: true

services:
  prometheus:
    # run as root, update to rootless mode later
    user: "0:0"
    hostname: prometheus
    container_name: prometheus
    image: ${MONITORING_PROMETHEUS_IMAGE_TAG}
    volumes:
      - ./prometheus/settings/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.size=256MB
    labels:dockr 
      - traefik.http.routers.prometheus.rule=Host(`p.${MONITORING_HOSTNAME}`)
      - traefik.http.routers.prometheus.service=prometheus
      - traefik.http.routers.prometheus.middlewares=auth
      - traefik.http.routers.prometheus.entrypoints=http
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
    networks:
      - monitoring-network
      - traefik-network
    restart: unless-stopped
    logging: *loki-logging

  grafana:
    # run as root, update to rootless mode later
    user: "0:0"
    hostname: grafana
    container_name: grafana
    image: grafana/grafana:10.0.5
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-settings:/etc/grafana/provisioning/
    labels:
      - traefik.http.routers.grafana.rule=Host(`g.${MONITORING_HOSTNAME}`)
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.routers.grafana.middlewares=auth
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entrypoints=http
    networks:
      - monitoring-network
      - traefik-network
    restart: unless-stopped
    logging: *loki-logging

  loki:
    # run as root, update to rootless mode later
    user: "0:0"
    hostname: loki
    container_name: loki
    image: grafana/loki:2.9.0
    command: -config.file=/mnt/config/loki-config.yml
    restart: unless-stopped
    volumes:
      - loki-data:/loki
      - ./loki/settings/loki-config.yml:/mnt/config/loki-config.yml
    ports:
      - 127.0.0.1:3100:3100
    networks:
      - monitoring-network
      - traefik-network
    labels:
      - traefik.http.routers.loki.rule=Host(`l.${MONITORING_HOSTNAME}`)
      - traefik.http.routers.loki.service=loki
      - traefik.http.routers.loki.middlewares=auth
      - traefik.http.services.loki.loadbalancer.server.port=3100
      - traefik.http.routers.loki.entrypoints=http
    logging: *loki-logging

  promtail:
    # run as root, update to rootless mode later
    user: "0:0"
    hostname: promtail
    container_name: promtail
    restart: unless-stopped
    image: grafana/promtail:2.9.0
    volumes:
      # logs for linux host only
      #- /var/log:/host/log
      - /var/lib/docker/containers:/host/containers
      - ./promtail/settings/promtail-config.yaml:/mnt/config/promtail-config.yaml
    command: -config.file /mnt/config/promtail-config.yaml
    networks:
      - monitoring-network
      - traefik-network
    logging: *loki-logging

  nodeexporter:
    image: prom/node-exporter:v1.6.1
    container_name: nodeexporter
    hostname: nodeexporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring-network
      - traefik-network
    logging: *loki-logging


  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8580:8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"