networks:
  orthanc-network:
    external: true
  traefik-network:
    external: true

volumes:
  orthanc-config:
    external: true
  orthanc-database:
    external: true

services:
  orthanc:
    container_name: orthanc
    image: jodogne/orthanc
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - orthanc-config:${ORTHANC_CONFIG_PATH}
      - orthanc-database:${ORTHANC_DATABASE_PATH}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orthanc.rule=Host(`${ORTHANC_HOSTNAME}`)"
      - "traefik.http.routers.orthanc.service=orthanc"
      - "traefik.http.routers.orthanc.entrypoints=websecure"
      - "traefik.http.services.orthanc.loadbalancer.server.port=8042"
      - "traefik.http.routers.orthanc.tls=true"
      - "traefik.http.routers.orthanc.tls.certresolver=letsencrypt"
      - "traefik.http.services.orthanc.loadbalancer.passhostheader=true"
      - "traefik.docker.network=traefik-network"
    networks:
      - orthanc-network
      - traefik-network