services:
  jira:
    # image: atlassian/jira-software:latest
    image: haxqer/jira:9.12.1
    restart: always
    container_name: jira
    environment:
      JVM_MINIMUM_MEMORY: 4g
      JVM_MAXIMUM_MEMORY: 12g
      VIRTUAL_HOST: jira.c1tech.group
      VIRTUAL_PORT: 8080
      ATLAS_OPTS: ' -Datlassian.dev.mode=false'
      ATL_PROXY_NAME: "jira.c1tech.group"
      ATL_TOMCAT_SECURE: 'true'
      ATL_TOMCAT_SCHEME: https
      ATL_PROXY_PORT: 443
      ATL_DB_TYPE: postgres72
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_JDBC_USER: jirauser
      ATL_JDBC_PASSWORD: PostgreSQLpass.24
      ATL_JDBC_URL: jdbc:postgresql://postgresql:5432/jiradb
      JVM_CODE_CACHE_ARGS: ' -XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
      TZ: Asia/Tehran
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
      # traefik:
      #   condition: service_healthy
    labels:
    # This is a special One!
      - "traefik.enable=true"
      - "traefik.http.routers.jira.rule=Host(`jira.c1tech.group`)"
      - "traefik.http.services.jira.loadbalancer.server.port=8080"
      - "traefik.http.routers.jira.entrypoints=secure"
      - "traefik.http.routers.jira.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.jira-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jira.service=jira"
      - "traefik.http.routers.jira.tls=true"
      - "traefik.http.services.jira.loadbalancer.passhostheader=true"
      - "traefik.http.routers.jira.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.docker.network=web"
    volumes:
      # - jira-data:/var/atlassian/application-data/jira:Z
      - jira-data:/var/jira:Z
    networks:
      - jira-network
      - traefik-network

  postgres:
    image: postgres:13
    restart: always
    container_name: jira-postgres
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jirauser
      POSTGRES_PASSWORD: PostgreSQLpass.24
      POSTGRES_INITDB_ARGS: --lc-collate C --lc-ctype C.UTF-8
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "jiradb", "-U", "jirauser" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - jira-postgres:/var/lib/postgresql/data
    networks:
      - jira-network

networks:
  jira-network:
    internal: true
  traefik-network:
    external: true

volumes:
  jira-postgres:
      external: true
  jira-data:
      external: true

