# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080


services:
  dockovpn:
    container_name: openvpn
    image: alekslitvinenk/openvpn
    cap_add:
        - NET_ADMIN
    ports:
        - 8099:80/tcp
        - 1194:1194/udp
    environment:
        HOST_ADDR: ${HOST_ADDR} 
    # volumes:
    #     - ./openvpn_conf:/opt/Dockovpn_data
    restart: unless-stopped