services:
  bitbucket:
    # image: atlassian/bitbucket-server:latest
    image: haxqer/bitbucket:7.21.16
    restart: always
    container_name: bitbucket
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/bitbucket
      - ATL_JDBC_USER=bitbucket
      - ATL_JDBC_PASSWORD=PostgreSQLpass.24
      - TZ=Asia/Tehran
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=12g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    # ports:
      # - "7990:7990"
      # - "7999:7999"
    depends_on:
      - postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitbucket.rule=Host(`bitbucket.c1tech.group`)"
      - "traefik.http.services.bitbucket.loadbalancer.server.port=7990"
      - "traefik.http.routers.bitbucket.entrypoints=secure"
      - "traefik.http.routers.bitbucket.tls.certresolver=letsencrypt"
    volumes:
      - bitbucket-bitbucket-data:/var/bitbucket:Z
    networks:
      - db
      - web

  postgresql:
    image: postgres:13
    restart: always
    container_name: bitbucket-postgres
    environment:
      POSTGRES_DB: bitbucket
      POSTGRES_USER: bitbucket
      POSTGRES_PASSWORD: PostgreSQLpass.24
    volumes:
      - bitbucket-postgresql-data:/var/lib/postgresql/data
    networks:
      - db

networks:
  db:
    internal: true
  web:
    external: true

volumes:
  bitbucket-postgresql-data:
      external: true
  bitbucket-bitbucket-data:
      external: true

