version: "3.5"
services:
  roundcubemail:
    image: roundcube/roundcubemail
    restart: always
    container_name: roundcubemail
    depends_on:
      - mysql
    # ports:
    #   - "8084:80"
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.hamid-najafi.ir
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.hamid-najafi.ir
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=Roundcubepass.24
      - ROUNDCUBEMAIL_DB_NAME=roundcubemail
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcubemail.rule=Host(`webmail.hamid-najafi.ir`)"
      - "traefik.http.services.roundcubemail.loadbalancer.server.port=80"
      - "traefik.http.routers.roundcubemail.entrypoints=secure"
      - "traefik.http.routers.roundcubemail.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik-network"
    volumes:
      - ./config:/var/roundcube/config/ 
    networks:
      - web
      - db
  mysql:
    image: mysql:5.7
    restart: always
    container_name: roundcubemail_db
    volumes:
      - mysqlDb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mySQLpass.24
      MYSQL_DATABASE: roundcubemail
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: Roundcubepass.24
    networks:
      - traefik-network
networks:
  db:
    internal: true
  web:
    external: true
volumes:
  mysqlDb: