networks:
  roundcubemail-network:
    external: true
  traefik-network:
    external: true

volumes:
  roundcubemail-postgres:
    external: true

version: "3.5"
services:
  roundcubemail:
    image: ${ROUNDCUBEMAIL_IMAGE_TAG}
    restart: always
    container_name: roundcubemail
    mysql:
      postgres:
        condition: service_healthy
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=${ROUNDCUBEMAIL_DEFAULT_HOST}
      - ROUNDCUBEMAIL_SMTP_SERVER=${ROUNDCUBEMAIL_SMTP_SERVER}
      - ROUNDCUBEMAIL_DB_TYPE=${ROUNDCUBEMAIL_DB_TYPE}
      - ROUNDCUBEMAIL_DB_HOST=${ROUNDCUBEMAIL_DB_HOST}
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=Roundcubepass.24
      - ROUNDCUBEMAIL_DB_NAME=roundcubemail
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcubemail.rule=Host(`webmail.hamid-najafi.ir`)"
      - "traefik.http.services.roundcubemail.loadbalancer.server.port=80"
      - "traefik.http.routers.roundcubemail.entrypoints=secure"
      - "traefik.http.routers.roundcubemail.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik-network"
    volumes:
      - ./config:/var/roundcube/config/
    networks:
      - web
      - db

  postgres:
    image: ${ROUNDCUBEMAIL_POSTGRES_IMAGE_TAG}
    container_name: roundcubemail-postgres
    volumes:
      - roundcubemail-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${ROUNDCUBEMAIL_DB_NAME}
      POSTGRES_USER: ${ROUNDCUBEMAIL_DB_USER}
      POSTGRES_PASSWORD: ${ROUNDCUBEMAIL_DB_PASSWORD}
    networks:
      - roundcubemail-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${ROUNDCUBEMAIL_DB_NAME}", "-U", "${ROUNDCUBEMAIL_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped