# https://www.keycloak.org/server/containers
version: "3.9"

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    command: start
    depends_on:
      - postgres
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB: postgres
      DB-URL: postgres
      DB-USERNAME: ${POSTGRESQL_USER}
      DB-PASSWORD: ${POSTGRESQL_PASS}
      HOSTNAME: keycloak
    restart: unless-stopped

volumes:
  postgres_data: