networks:
  nextcloud-network:
    external: true
  traefik-network:
    external: true

volumes:
  nextcloud-data:
    external: true
  nextcloud-postgres:
    external: true
  nextcloud-redis:
    external: true
  clamav-socket:
    external: true
  clamav-db:
    external: true


services:
  nextcloud:
    image: ${NEXTCLOUD_IMAGE_TAG}
    container_name: nextcloud
    volumes:
      - nextcloud-data:${NEXTCLOUD_DATA_PATH}
    environment:
      # https://github.com/nextcloud/docker
      # Time & PHP
      TZ: ${NEXTCLOUD_TIMEZONE}
      PHP_MEMORY_LIMIT: ${NEXTCLOUD_PHP_MEMORY_LIMIT}
      PHP_UPLOAD_LIMIT: ${NEXTCLOUD_PHP_UPLOAD_LIMIT}
      PHP_OPCACHE_MEMORY_CONSUMPTION: ${NEXTCLOUD_PHP_OPCACHE_MEMORY_CONSUMPTION}
      # Admin User
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      # Database
      POSTGRES_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      # Redis
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${NEXTCLOUD_REDIS_PASSWORD}
      # URLs and Trusted Settings
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      OVERWRITEHOST: ${NEXTCLOUD_HOSTNAME}
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: ${NEXTCLOUD_URL}
      TRUSTED_PROXIES: ${NEXTCLOUD_PROXIES}
    networks:
      - nextcloud-network
      - traefik-network
    # ports:
    #  - 8080:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      # Router Nextcloud
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.services.nextcloud.loadbalancer.passhostheader=true"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex@docker,nextcloud-headers"
      # Redirect .well-known/caldav → /remote.php/dav
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"
      # HSTS Headers
      - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true"
      # Redirect ALT -> MAIN
      - "traefik.http.routers.nextcloud_redirect.rule=Host(`${NEXTCLOUD_HOSTNAME_ALT}`)"
      - "traefik.http.routers.nextcloud_redirect.entrypoints=websecure"
      - "traefik.http.routers.nextcloud_redirect.tls=true"
      - "traefik.http.routers.nextcloud_redirect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextcloud_redirect.middlewares=nextcloud_redirect_alt@docker"
      - "traefik.http.middlewares.nextcloud_redirect_alt.redirectregex.regex=https://${NEXTCLOUD_HOSTNAME_ALT}(.*)"
      - "traefik.http.middlewares.nextcloud_redirect_alt.redirectregex.replacement=https://${NEXTCLOUD_HOSTNAME}$${1}"
      - "traefik.http.middlewares.nextcloud_redirect_alt.redirectregex.permanent=true"
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  nextcloud-cron:
    image: ${NEXTCLOUD_IMAGE_TAG}
    container_name: nextcloud-cron
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
    networks:
      - nextcloud-network

  postgres:
    image: ${NEXTCLOUD_POSTGRES_IMAGE_TAG}
    container_name: nextcloud-postgres
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
    networks:
      - nextcloud-network
    # ports:
    #   - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${NEXTCLOUD_DB_NAME}", "-U", "${NEXTCLOUD_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  redis:
    image: ${NEXTCLOUD_REDIS_IMAGE_TAG}
    container_name: nextcloud-redis
    command: ["redis-server", "--requirepass", "${NEXTCLOUD_REDIS_PASSWORD}"]
    volumes:
      - nextcloud-redis:/data
    networks:
      - nextcloud-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  clamav:
    image: "clamav/clamav:stable_base"
    container_name: "clamav"
    healthcheck:
      test: ["CMD-SHELL", "clamdscan --version || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      # Socket
      - clamav-socket:/var/run/clamav/
      # Virus DB
      - clamav-db:/var/lib/clamav/
    restart: unless-stopped