{
 "title": "BigBlueButton Server Instance (netdata)",
 "tags": [
  "BigBlueButton",
  "prometheus",
  "netdata"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bbb_exporter, job)"
   },
   {
    "name": "job_netdata",
    "label": "Job Netdata",
    "query": "label_values(netdata_system_cpu_percentage_average, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bbb_api_up, instance)"
   },
   {
    "name": "interface",
    "label": "Network Interface",
    "query": "label_values(netdata_net_net_kilobits_persec_average, family)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BBB API",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_api_up{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "BigBlueButton Exporter Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bbb_exporter{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Type of Users Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    },
    {
     "expr": "bbb_meetings_listeners{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Listeners"
    },
    {
     "expr": "bbb_meetings_voice_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Voice"
    },
    {
     "expr": "bbb_meetings_video_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Video"
    }
   ]
  },
  {
   "title": "CPU Utilization vs. Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utlization [%]" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_system_cpu_percentage_average{job=\"$job_netdata\", dimension!=\"idle\", instance=\"$instance\"})",
     "legendFormat": "CPU Utlization"
    },
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Bandwidth vs. Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "Kbits", "label": "Bandwidth" }
   ],
   "targets": [
    {
     "expr": "abs(netdata_net_net_kilobits_persec_average{job=\"$job_netdata\", instance=\"$instance\", family=\"$interface\"})",
     "legendFormat": "{{family}} ({{dimension}})"
    },
    {
     "expr": "bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Participants"
    }
   ]
  },
  {
   "title": "Max Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(bbb_meetings_participants{job=\"$job\", instance=\"$instance\"})",
     "legendFormat": "Selected timeframe"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}[1w])",
     "legendFormat": "Since 1 week"
    },
    {
     "expr": "max_over_time(bbb_meetings_participants{job=\"$job\", instance=\"$instance\"}[100y])",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "Participants Origin",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participants_origin{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of Rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Rooms" }
   ],
   "targets": [
    {
     "expr": "bbb_room_participants_gcount{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Rooms"
    }
   ]
  },
  {
   "title": "Voice Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_voice_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Voice participants"
    }
   ]
  },
  {
   "title": "Video Participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Video Participants" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_video_participants{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Video participants"
    }
   ]
  },
  {
   "title": "Recordings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bbb_recordings_processing{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Processing"
    },
    {
     "expr": "bbb_recordings_unprocessed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Unprocessed"
    },
    {
     "expr": "bbb_recordings_published{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Published"
    },
    {
     "expr": "bbb_recordings_unpublished{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Unpublished"
    },
    {
     "expr": "bbb_recordings_deleted{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (netdata_disk_space_GiB_average{job=\"$job_netdata\", instance=\"$instance\", dimension=\"avail\"} / ignoring(dimension) (netdata_disk_space_GiB_average{job=\"$job_netdata\", instance=\"$instance\", dimension=\"avail\"} + ignoring(dimension) netdata_disk_space_GiB_average{job=\"$job_netdata\", instance=\"$instance\", dimension=\"used\"} + ignoring(dimension) netdata_disk_space_GiB_average{job=\"$job_netdata\", instance=\"$instance\", dimension=\"reserved for root\"}))",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Recordings Unprocessed",
   "type": "graph",
   "description": "Requires `RECORDINGS_METRICS_READ_FROM_DISK` to be enabled on the BigBlueButton Exporter",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Recordings " }
   ],
   "targets": [
    {
     "expr": "bbb_recordings_unprocessed{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Recordings Unprocessed "
    }
   ]
  },
  {
   "title": "Participants by Client Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bbb_meetings_participant_clients{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Heatmaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Heatmap of Room Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "bbb_room_participants_bucket{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Listeners Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of listeners while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "bbb_room_listeners_bucket{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Voice Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of voice participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "bbb_room_voice_participants_bucket{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap of Video Participants",
   "type": "heatmap",
   "description": "Buckets (Y axis) represents the number of video participants while the count in each bucket represents the number of rooms with that particular bucket's value. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "bbb_room_video_participants_bucket{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Exporter Metrics Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", instance=\"$instance\"}[5m])) by (le, instance, endpoint, parameters))) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BigBlueButton API Response Time (95th Percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getMeetings\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getMeetings"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processing\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processing"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=processed\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings processed"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=published\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings published"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=unpublished\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings unpublished"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bbb_api_latency_bucket{job=\"$job\", endpoint=\"getRecordings\", parameters=\"state=deleted\", instance=\"$instance\"}[5m])) by (le, instance))",
     "legendFormat": "getRecordings deleted"
    }
   ]
  }
 ]
}