networks:
  traefik-network:
    external: true

volumes:
  traefik-certificates:
    external: true

services:
  traefik:
    image: ${TRAEFIK_IMAGE_TAG}
    container_name: traefik
    environment:
      - TZ=${TRAEFIK_TIMEZONE}
    volumes:
      # Mount the Docker socket so Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Main static configuration file
      # - ./traefik.yml:/etc/traefik/traefik.yml
      # Dynamic configuration folder (for middlewares, routers, etc.)
      - ./dynamic_conf:/etc/traefik/dynamic_conf
      # Volume for Let's Encrypt certificates storage
      - traefik-certificates:/etc/traefik/acme
    networks:
      - traefik-network
    ports:
      # HTTP
      - "80:80"
      # HTTPS (TCP)
      - "443:443"      
      # QUIC / HTTP3 (UDP)
      - "443:443/udp"   
      # Ping
      - "8082:8082"
      # Zabbix TCP
      - "10051:10051"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    command:
      # -------- Logging & API --------
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=true"

      # -------- Ping --------
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entrypoints.ping.address=:8082"

      # -------- EntryPoints --------
      - "--entrypoints.webinsecure.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3=true"         # << QUIC/HTTP3
      - "--entrypoints.webinsecure.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.webinsecure.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.zabbix-tcp.address=:10051"
      - "--entrypoints.zabbix-udp.address=:10051/udp"

      # -------- Providers --------
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"

      # -------- Certificates --------
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"

      # -------- Metrics --------
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"

      # -------- Global options --------
      - "--global.checknewversion=true"
      - "--global.sendanonymoususage=false"
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"

      # -------- Traefik Dashboard --------
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.middlewares=authentik@docker"

      # Redirect HTTP → HTTPS
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=webinsecure"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Enable compression
      - "traefik.http.middlewares.compress.compress=true"
    restart: unless-stopped