# Traefik Envoronment Variables Comes Here (Traefik.yml)
# ((Example))
  # command:
  #   - "--log.level=DEBUG"
# ((Will be))
  # log:
  #   level:
  #     DEBUG

# Dynamic configuration will come from docker labels