networks:
  influxdb-network:
    external: true
  
volumes:
  influxdb-data:
    external: true
  influxdb-config:
    external: true

services:
  influxdb:
    image: ${INFLUXDB_IMAGE_TAG}
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: ${INFLUXDB_INIT_RETENTION}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - influxdb-config:/etc/influxdb
      - influxdb-data:/var/lib/influxdb
    restart: unless-stopped
    networks:
      - influxdb-network

  telegraf:
    image: ${TELEGRAF_IMAGE_TAG} 
    container_name: telegraf
    restart: always
    privileged: true
    user: "root"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # Mount the Telegraf configuration file
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount the Docker socket to collect Docker metrics
    depends_on:
      - influxdb
    ports:
      - '8125:8125'  # Expose Telegraf's StatsD port
    networks:
      - influxdb-network