version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    restart: always
    hostname: ir.hamid-najafi.ir
    ports:
      - 2308:2308
    volumes:
      - ${PWD}/config.json:/etc/v2ray/config.json
      - ${PWD}/log/:/var/log/v2ray/