http:
  routers:
    gpu-http:
      rule: "Host(`gpu-traefik.c1tech.group`)"
      service: gpu-service
      entryPoints:
        - webinsecure

    gpu-https:
      rule: "Host(`gpu-traefik.c1tech.group`)"
      service: gpu-service
      entryPoints:
        - websecure

  services:
    gpu-service:
      loadBalancer:
        servers:
          - url: "http://172.25.10.25:80"
        passHostHeader: true