# Traefik Envoronment Variables Comes Here (Traefik.yml)
# ((Example))
  # command:
  #   - "--log.level=DEBUG"
# ((Will be))
  # log:
  #   level:
  #     DEBUG


api:
  dashboard: true
  insecure: true

log:
  level:
    DEBUG

accesslog: true

ping:
  entryPoint: "ping"

global:
  checkNewVersion: true
  sendAnonymousUsage: false
  
#Define HTTP and HTTPS entrypoints
entryPoints:
  insecure:
    address: ":80"
  secure:
    address: ":443"
  metrics:
    address: ":9094"
  ping:
    address: ":8082"
  # zabbix-tcp:
  #   address: ":8082"
  # zabbix-udp:
  #   address: ":10051/udp"

#Dynamic configuration will come from docker labels
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false

#Enable acme with http file challenge
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@c1tech.group
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: insecure

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets: 0.1,0.3,1.2,5.0