# Traefik Envoronment Variables Comes Here (Traefik.yml)
# ((Example))
  # command:
  #   - "--log.level=DEBUG"
# ((Will be))
  # log:
  #   level:
  #     DEBUG


api:
  dashboard: true
  insecure: true

log:
  level:
    DEBUG

accesslog: true

ping:
  entryPoint: "ping"

global:
  checkNewVersion: true
  sendAnonymousUsage: false
 
# These are handeled in authentik docker compose
# http:
#   middlewares:
#     authentik:
#       forwardauth:
#         address: http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
#         trustForwardHeader: true
#         authResponseHeaders:
#           - X-authentik-username
#           - X-authentik-groups
#           - X-authentik-email
#           - X-authentik-name
#           - X-authentik-uid
#           - X-authentik-jwt
#           - X-authentik-meta-jwks
#           - X-authentik-meta-outpost
#           - X-authentik-meta-provider
#           - X-authentik-meta-app
#           - X-authentik-meta-version
# These are handeled in authentik docker compose

#Define HTTP and HTTPS entrypoints
entryPoints:
  webinsecure:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":9094"
  ping:
    address: ":8082"
  ssh:
    address: ":22"
  # zabbix-tcp:
  #   address: ":8082"
  # zabbix-udp:
  #   address: ":10051/udp"

#Dynamic configuration will come from docker labels
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

#Enable acme with http file challenge
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@c1tech.group
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: webinsecure
        # used during the challenge
        
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets: 0.1,0.3,1.2,5.0