version: '2.3'

services:
  redis:
    restart: always
    image: redis:6.2.6
    container_name: gitlab-redis
    command:
    - --loglevel warning
    volumes:
    - gitlab-redis-data:/data:Z
    networks:
      - traefik-network

  postgresql:
    restart: always
    container_name: gitlab-postgresql
    image: sameersbn/postgresql:14-20230628
    volumes:
    - gitlab-postgresql-data:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=PostgreSQLpass.24
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm,btree_gist
    networks:
      - traefik-network

  gitlab:
    restart: always
    image: sameersbn/gitlab:16.6.2
    container_name: gitlab
    depends_on:
    - redis
    - postgresql
    # Handeled By Traefik
    # ports:
    # - "10080:80"
    # - "10022:22"
    volumes:
    - gitlab-gitlab-data:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=PostgreSQLpass.24
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Tehran
    - GITLAB_TIMEZONE=Asia/Tehran

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=PXpHn4wW3JzdkpHkg4XXRHjsFnNHgnwwtkVMbpJTbKR7wFwN49CmqJKNrbPxXqsM
    - GITLAB_SECRETS_SECRET_KEY_BASE=mP9KrFkw4JkLNPmn9FxgFKgWR9bRm9RPqsbh77nvxrFFvtxgJ9hsNhsnmgndFhsJ
    - GITLAB_SECRETS_OTP_KEY_BASE=NRdfn3PPWThrjtmkvc3nwVrRkNKPzw93sgFFjr73XfhsPMmFwgmrFk33JRtT9jzt

    - GITLAB_ROOT_PASSWORD=5iveL!fe
    - GITLAB_ROOT_EMAIL=admin@c1tech.group

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@c1tech.group
    - GITLAB_EMAIL_REPLY_TO=noreply@c1tech.group
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@c1tech.group

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@c1tech.group
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@c1tech.group
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - LDAP_ENABLED=true
    - LDAP_LABEL=C1TechLDAP
    - LDAP_HOST=172.25.10.5
    - LDAP_PORT=389
    - LDAP_UID=sAMAccountName
    - LDAP_METHOD=plain
    - LDAP_VERIFY_SSL=false
    - LDAP_BIND_DN=CN=Administrator,CN=Users,DC=C1Tech,DC=local
    - LDAP_PASS=C1Techpass.DC
    - LDAP_ACTIVE_DIRECTORY=true
    - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=true
    - LDAP_BLOCK_AUTO_CREATED_USERS=false
    - LDAP_BASE=OU=Users,OU=C1Tech,DC=C1Tech,DC=local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.c1tech.group`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.routers.gitlab.entrypoints=secure"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
    networks:
      - traefik-network
      - web

networks:
  db:
    internal: true
  web:
    external: true
volumes:
  gitlab-redis-data:
      external: true
  gitlab-postgresql-data:
      external: true
  gitlab-gitlab-data:
      external: true