# Set up the volumes location
# export GITLAB_HOME=/srv/gitlab

version: "3.5"
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.hamid-najafi.ir'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.hamid-najafi.ir:80'
        gitlab_rails['time_zone'] = 'Asia/Tehran'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail.hamid-najafi.ir"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "admin@hamid-najafi.ir"
        gitlab_rails['smtp_password'] = "Mailpass.24"
        gitlab_rails['smtp_domain'] = "mail.hamid-najafi.ir"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = 'gitlab@hamid-najafi.ir'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@hamid-najafi.ir'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '2222:22'
      - '8087:80'
    # - '443:443'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.hamid-najafi.ir`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.routers.gitlab.entrypoints=secure"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
    networks:
      - default

networks:
  default:
    external:
      name: gateway