version: "3.5"
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.c1tech.group'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.c1tech.group:80'
        gitlab_rails['time_zone'] = 'Asia/Tehran'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mail.c1tech.group"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "admin@c1tech.group"
        gitlab_rails['smtp_password'] = "Mailpass.24"
        gitlab_rails['smtp_domain'] = "mail.c1tech.group"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = 'gitlab@c1tech.group'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@c1tech.group'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = {
          'main' => {
            'label' => 'LDAP',
            'host' =>  '172.25.10.5',
            'port' => 389,
            'uid' => 'sAMAccountName',
            'encryption' => 'plain',
            'bind_dn' => 'CN=Administrator,CN=Users,DC=C1Tech,DC=local',
            'password' => 'C-One@135Dn',
            'active_directory' => true,
            'allow_username_or_email_login' => true,
            'block_auto_created_users' => false,
            'base' => 'OU=Users,OU=C1Tech,DC=C1Tech,DC=local',
            'attributes' => {
              'username' => ['uid', 'userid', 'sAMAccountName'],
              'email' =>    ['mail', 'email', 'userPrincipalName'],
              'name' =>      'cn',
              'first_name' => 'givenName',
              'last_name' =>  'sn'
              }
          }
        }
    # Handeled by Traefik
    # ports:
    #   - '8087:80'
    #   - '443:443'
    #   - '587:587'
    #   - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.c1tech.group`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.http.routers.gitlab.entrypoints=secure"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
    networks:
      - web
networks:
  web:
    external: true