
services:
  squid:
    image: sameersbn/squid
    container_name: squid
    restart: unless-stopped
    ports:
      - "3128:3128"
    volumes:
      - ${PWD}/squid.conf:/etc/squid/squid.conf
      - ${PWD}/passwords:/etc/squid/passwords
      - /srv/docker/squid/cache:/var/spool/squid