http:
  routers:
    jupyter:
      service: jupyter
      rule: "Host(`jupyter.c1tech.group`)"
      entryPoints:
        - websecure
      tls:
        certresolver: letsencrypt
      middlewares:
        - authentik@docker
  services:
    jupyter:
      loadBalancer:
        servers:
          - url: "http://172.25.10.25:17256"
        passHostHeader: true