http:
  routers:
    xprotect:
      rule: "Host(`xprotect.c1tech.group`)"
      service: xprotect
      entryPoints:
        - websecure
      tls:
        certresolver: letsencrypt
  services:
    xprotect:
      loadBalancer:
        servers:
          - url: "http://172.25.10.12:8081"
        passHostHeader: true

