version: '3'
services:
  shadowsocksr:
    image:  teddysun/shadowsocks-r
    container_name: shadowsocks-r
    restart: unless-stopped
    ports:
      - 8388:8388/udp
      - 8388:8388
    volumes:
      - ${PWD}/:/etc/shadowsocks-r