version: "3.5"
services:
  mongodb:
    image: mongo
    hostname: mongo.goldenstarc.ir
    # container_name: mongodb
    restart: always
    # env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoDBpass.24
    # ports:
    #   - "27017:27017"
    volumes:
      - mongoDb:/data/db
    networks:
      - db
  adminer:
    image: adminer
    # container_name: adminer
    environment:
      ADMINER_DESIGN: mvt
      # - ADMINER_PLUGINS='tables-filter tinymce'
      # - ADMINER_PLUGINS='login-servers'
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    #   - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.goldenstarc.ir`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=secure"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"
    networks:
      - db
      - web
networks:
  db:
    internal: true
  web:
    external: true
volumes:
  mongoDb: