version: "3.5"
services:
  postgres:
    image: postgres
    hostname: postgres.c1tech.group
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PostgreSQLpass.24
    volumes:
      - postgresql-postgresql-data:/var/lib/postgresql/data
    networks:
      - db
      - web
  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin.c1tech.group
    container_name: postgres-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@c1tech.group
      - PGADMIN_DEFAULT_PASSWORD=pgAdminpass.24
    restart: unless-stopped
    # Handeled by traefik
    # ports:
    # - "8081:80"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.c1tech.group`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.entrypoints=secure"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"
    volumes:
       - postgresql-pgadmin-data:/var/lib/pgadmin
    networks:
      - db
      - web
networks:
  db:
    internal: true
  web:
    external: true
volumes:
  postgresql-postgresql-data:
    external: true
  postgresql-pgadmin-data:
    external: true