networks:
  postgres-network:
    external: true
  traefik-network:
    external: true

volumes:
  postgres-data:
    external: true
  postgres-pgadmin:
    external: true

version: "3.5"
services:
  postgres:
    image: ${POSTGRES_IMAGE_TAG}
    hostname: ${POSTGRES_HOSTNAME}
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB_NAME}", "-U", "${POSTGRES_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: ${PGADMIN_IMAGE_TAG}
    hostname: ${PGADMIN_HOSTNAME}
    container_name: postgres-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERNAME}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    restart: unless-stopped
    # Handeled by traefik
    # ports:
    # - "8081:80"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_HOSTNAME}`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.service=pgadmin"
      - "traefik.http.routers.pgadmin.entrypoints=secure"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pgadmin.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.docker.network=traefik-network"
    volumes:
       - postgres-pgadmin:/var/lib/pgadmin
    networks:
      - postgres-network
      - traefik-network