global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    scheme: http
    basic_auth:
      username: "admin"
      password: "Metricpass.24"
    static_configs:
      - targets: ['su.legace.ir:9100', 'b1.legace.ir:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    scheme: http
    basic_auth:
      username: "admin"
      password: "Metricpass.24"
    static_configs:
      - targets: ['su.legace.ir:9338', 'b1.legace.ir:9338']

  - job_name: 'traefik'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    basic_auth:
      username: "traefik"
      password: "Traefikpass.24"
    static_configs:
      - targets: ['traefik:9094']

  - job_name: minio
    # bearer_token: <secret>
    metrics_path: /minio/prometheus/metrics
    scheme: http
    static_configs:
    - targets: ['minio.legace.ir']

  - job_name: 'bbb'
    scrape_interval: 5s
    scheme: https
    basic_auth:
      username: "metrics"
      password: "monitor@bbb"
    static_configs:
    - targets: ['b1.legace.ir']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
