networks:
  traefik-network:
    external: true
  v2raya-network:
    external: true

version: "3.5"

services:
  v2raya:
    image: ${V2RAYA_IMAGE_TAG}
    restart: unless-stopped
    container_name: v2raya
    ports:
      # - 2017:2017 (Admin Panel)
      - 20170-20172:20170-20172
      - 20170-20172:20170-20172/udp
    environment:
      - V2RAYA_LOG_FILE=${V2RAYA_LOG_FILE}
      - V2RAYA_V2RAY_BIN=${V2RAYA_V2RAY_BIN}
      - V2RAYA_NFTABLES_SUPPORT=${V2RAYA_NFTABLES_SUPPORT}
      - IPTABLES_MODE=${IPTABLES_MODE}
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/v2raya:/etc/v2raya
      - /usr/share/v2ray:/usr/share/v2ray
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.v2raya.rule=Host(`${V2RAYA_HOSTNAME}`)"
      - "traefik.http.services.v2raya.loadbalancer.server.port=2017"
      - "traefik.http.routers.v2raya.entrypoints=websecure"
      - "traefik.http.routers.v2raya.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik-network"
    # networks:
    #   - traefik-network
    #   - v2raya-network
    network_mode: host