version: '3'
services:
  ocserv:
    image:  tommylau/ocserv
    container_name: ocserv
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
#      - ${PWD}/ocpasswd:/etc/ocserv/ocpasswd
      - ${PWD}/ocserv.conf:/etc/ocserv/ocserv.conf
      - /etc/letsencrypt/:/etc/letsencrypt/