version: '3'
services:
  ocserv:
    image:  tommylau/ocserv
    container_name: ocserv
    restart: always
    privileged: true
    hostname: ir.hamid-najafi.ir
    ports:
      - 443:443/udp
      - 443:443
    volumes:
      # - ${PWD}/ocpasswd:/etc/ocserv/ocpasswd
      - ${PWD}/ocserv.conf:/etc/ocserv/ocserv.conf
      - /etc/letsencrypt/:/etc/letsencrypt/