

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: unless-stopped
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
