volumes:
  coturn-logs:
    external: true

networks:
  coturn-network:
    external: true
  traefik-network:
    external: true

services:
  coturn:
    image: ${COTURN_IMAGE_TAG}
    container_name: coturn
    hostname: turn
    restart: unless-stopped
    environment:
      # timezone inside container
      - TZ=${COTURN_TIMEZONE}
    volumes:
      # - coturn-logs:/var/log:rw
      - ./turnserver.conf:/etc/turnserver.conf:ro
      # TODO You need to generate Let's Encrypt certificates for ${COTURN_HOSTNAME}
      - /etc/letsencrypt/live/${COTURN_HOSTNAME}:/etc/letsencrypt/live/${COTURN_HOSTNAME}:ro
      - /etc/letsencrypt/archive/${COTURN_HOSTNAME}:/etc/letsencrypt/archive/${COTURN_HOSTNAME}:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    user: root
    network_mode: host