services:
  ntp:
    image: ${CHRONY_IMAGE_TAG}
    container_name: ntp
    hostname: ntp
    restart: unless-stopped
    ports:
      - 123:123/udp
      - 4460:4460/tcp
    environment:
      - NTP_SERVERS=${CHRONY_NTP_SERVERS}
      - LOG_LEVEL=${CHRONY_LOG_LEVEL}
      - TZ=${CHRONY_TIMEZONE}
      - NOCLIENTLOG=${CHRONY_NOCLIENTLOG}
      - ENABLE_NTS=${CHRONY_ENABLE_NTS}
    volumes:
      # # NOT SUPPORTED 
      - /etc/letsencrypt/live/${CHRONY_HOSTNAME}/fullchain.pem:/opt/fullchain.pem:ro
      - /etc/letsencrypt/live/${CHRONY_HOSTNAME}/privkey.pem:/opt/privkey.pem:ro