# networks:
#   traefik-network:
#     external: true

volumes:
  jupyter-opt:
    external: true
  jupyter-work:
    external: true
  jupyter-env:
    external: true

services:
  jupyter:
    image: ${JUPYTER_IMAGE_TAG}
    hostname: jupyter
    container_name: jupyter
    restart: unless-stopped
    environment:
      - CHOWN_EXTRA=/home/${JUPYTER_NOTEBOOK_USER}/work
      - CHOWN_EXTRA_OPTS=-R
      # - NB_UID=1000
      # - NB_GID=100
      - NB_UID=0
      - NB_GID=0
      - NB_USER=${JUPYTER_NOTEBOOK_USER}
      - NB_GROUP=users
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    command: >
      start-notebook.py
      --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.allow_origin='*'
      --NotebookApp.ip='0.0.0.0'
      --NotebookApp.allow_root=True
      --NotebookApp.disable_check_xsrf=True
    ports:
      - "8888:8888"
    volumes:
      - jupyter-opt:/opt
      - jupyter-work:/home/${JUPYTER_NOTEBOOK_USER}/work
      - jupyter-env:/home/${JUPYTER_NOTEBOOK_USER}/work/environments
    working_dir: /home/${JUPYTER_NOTEBOOK_USER}/work
    user: root
    env_file:
      - .env

