
networks:
  # uptimekuma-network:
  #   external: true
  traefik-network:
    external: true

volumes:
  uptimekuma-data:
    external: true
  uptimekuma-server:
    external: true
  uptimekuma-db:
    external: true

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: ${UPTIMEKUMA_IMAGE_TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptimekuma-data:/app/data
      - uptimekuma-server:/app/server
      - uptimekuma-db:/app/db
    ports:
      # - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`${UPTIMEKUMA_HOSTNAME}`)"
      - "traefik.http.routers.uptimekuma.service=uptimekuma"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
      - "traefik.http.routers.uptimekuma.tls=true"
      - "traefik.http.routers.uptimekuma.tls.certresolver=letsencrypt"
      - "traefik.http.services.uptimekuma.loadbalancer.passhostheader=true"
      - "traefik.http.routers.uptimekuma.middlewares=traefik-compress"
      - "traefik.http.middlewares.traefik-compress.compress=true"
      - "traefik.http.routers.uptimekuma.middlewares=authentik@docker"
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped