version: '3.7'
services:
  minio:
    image: minio/minio:latest
    restart: always
    volumes:
      - /mnt/data:/data
    ports:
      - "9000:9000" #S3 Service
      - "9001:9001" #Console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: MinIOpass.24
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3.rule=Host(`s3.hamid-najafi.ir`)"
      - "traefik.http.routers.s3.service=s3"
      - "traefik.http.services.s3.loadbalancer.server.port=9000"
      - "traefik.http.routers.s3.entrypoints=secure"
      - "traefik.http.routers.s3.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio.rule=Host(`minio.hamid-najafi.ir`)"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio.entrypoints=secure"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"
    networks:
      - web
networks:
  web:
    external: true
