networks:
  traefik-network:
    external: true

volumes:
  grafana-data:
    external: true
  grafana-settings:
    external: true

x-logging: &grafana-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  grafana:
    user: "0:0"
    hostname: grafana
    container_name: grafana
    image: ${GRAFANA_IMAGE_TAG}
    ports:
      - 3000:3000/tcp
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/
    labels:
      - traefik.http.routers.grafana.rule=Host(`g.${GRAFANA_HOSTNAME}`)
      - traefik.http.routers.grafana.service=grafana
      - traefik.http.routers.grafana.entrypoints=http
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - traefik-network
    restart: unless-stopped
    logging: *grafana-logging
