version: "3.5"
services:
  moodle:
    image: 'goldenstarc/moodle:latest'
    restart: always
    ports:
      - '8086:8080'
#      - '443:8443'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=Bitnamipass.24
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=wydta4-voqvAb-vadpaf
      - MOODLE_EMAIL=admin@hamid-najafi.ir
      - MOODLE_SITE_NAME=Virgol
      - MOODLE_SMTP_HOST=mail.hamid-najafi.ir
      - MOODLE_SMTP_PORT=587
      - MOODLE_SMTP_USER=noreply@hamid-najafi.ir
      - MOODLE_SMTP_PASSWORD=Mailpass.24
      - MOODLE_SMTP_PROTOCOL=tls
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle.rule=Host(`moodle2.vir-gol.ir`)"
      - "traefik.http.services.moodle.loadbalancer.server.port=8080"
      - "traefik.http.routers.moodle.entrypoints=secure"
      - "traefik.http.routers.moodle.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"
    volumes:
      - moodle:/bitnami/moodle
      - moodleData:/bitnami/moodledata
      # - '/docker/moodle-bitnami:/bitnami/moodle'
      # - '/docker/moodle-data-bitnami:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - db
      - web

  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=mySQLpass.24
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_PASSWORD=Bitnamipass.24
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariaDb:/bitnami/mariadb
      # - '/docker/mariadb-bitnami:/bitnami/mariadb'
    networks:
      - db
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
    restart: always
    environment:
      - PMA_ABSOLUTE_URI=https://phpmyadmin.hamid-najafi.ir/
      - PMA_HOST=mariadb
      # - PMA_ARBITRARY=1
    ports:
      - '8082:8080'
#      - '443:8443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.hamid-najafi.ir`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=8080"
      - "traefik.http.routers.phpmyadmin.entrypoints=secure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"
    depends_on:
      - mariadb
    networks:
      - db
      - web

networks:
  db:
    internal: true
  web:
    external: true

volumes:
  moodle:
  moodleData:
  mariaDb: