services:
  confluence:
    # image: atlassian/confluence-server:latest
    image: haxqer/confluence:8.7.1
    restart: always
    container_name: confluence
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/confluence
      - ATL_JDBC_USER=confluence
      - ATL_JDBC_PASSWORD=PostgreSQLpass.24
      - TZ=Asia/Tehran
      - JVM_MINIMUM_MEMORY=1g
      - JVM_MAXIMUM_MEMORY=12g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    # ports:
    #   - 8080:8080
    depends_on:
      - postgresql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.confluence.rule=Host(`confluence.c1tech.group`)"
      - "traefik.http.services.confluence.loadbalancer.server.port=8080"
      - "traefik.http.routers.confluence.entrypoints=secure"
      - "traefik.http.routers.confluence.tls.certresolver=letsencrypt"
    volumes:
      - confluence-confluence-data:/var/confluence:Z
    networks:
      - db
      - web

  postgresql:
    image: postgres:13
    restart: always
    container_name: confluence-postgres
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: PostgreSQLpass.24
    volumes:
      - confluence-postgresql-data:/var/lib/postgresql/data
    networks:
      - db

networks:
  db:
    internal: true
  web:
    external: true

volumes:
  confluence-postgresql-data:
      external: true
  confluence-confluence-data:
      external: true

