version: "3.5"
services:
  virgol:
    image: goldenstarc/virgol:latest
    restart: always
    container_name: virgol_main2
    volumes:
      - virgol2Data:/app/BulkData
    # build:
    #   context: .
    environment:
      - ASPNETCORE_URLS=http://+ # ;https://+
      - ASPNETCORE_ENVIRONMENT=Production
      - NODE_ENV=production
      - VIRGOL_SERVER_ROOT_URL=https://javanehha2.vir-gol.ir
      - VIRGOL_DATABASE_HOST=virgol_db
      - VIRGOL_DATABASE_PORT=5432
      - VIRGOL_DATABASE_NAME=Virgol
      - VIRGOL_DATABASE_USER=postgres
      - VIRGOL_DATABASE_PASSWORD=PostgreSQLpass.24
      - VIRGOL_MOODLE_BASE_URL=https://moodle.vir-gol.ir
      - VIRGOL_MOODLE_TOKEN=f6b34b01c4c660329a9e95a5ed349946
      - VIRGOL_Default_SMSProvider=Faraz
      - VIRGOL_FARAZAPI_URL=http://rest.ippanel.com
      - VIRGOL_FARAZAPI_SENDER_NUMBER=+98500010707
      - VIRGOL_FARAZAPI_USERNAME=goldenstarc
      - VIRGOL_FARAZAPI_PASSWORD=hektug-fakbAm-0vypje
      - VIRGOL_FARAZAPI_API_KEY=qcP4IQp3PPRV3ppvkG9ScHJcwvUPL3iOJrV9n7QiqDA=
      - VIRGOL_JWT_SECRET=Saleh Secret Key
      - VIRGOL_LDAP_SERVER=virgol_openldap
      - VIRGOL_LDAP_PORT=389
      - VIRGOL_LDAP_USER_ADMIN=cn=admin,dc=legace,dc=ir
      - VIRGOL_LDAP_PASSWORD=OpenLDAPpass.24
      - VIRGOL_TZ=Asia/Tehran
      # - VIRGOL_SMTP_HOST
      # - VIRGOL_SMTP_PASS
      # - VIRGOL_SMTP_PORT
      # - VIRGOL_SMTP_USER
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.virgol.rule=Host(`javanehha2.vir-gol.ir`)"
      - "traefik.http.services.virgol.loadbalancer.server.port=80"
      - "traefik.http.routers.virgol.entrypoints=secure"
      - "traefik.http.routers.virgol.tls.certresolver=letsencrypt"
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.virgol_compress.compress=true"
      - "traefik.http.routers.virgol.middlewares=virgol_compress"
    networks:
      - virgol
      - web
    depends_on:
      - postgres
      - openldap
  postgres:
    image: postgres
    container_name: virgol_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      # - POSTGRES_DB=virgol
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PostgreSQLpass.24
    volumes:
      - postgresDb:/var/lib/postgresql/data
    networks:
      - virgol
      - web
networks:
  virgol:
    internal: true
  web:
    external: true
volumes:
  virgol2Data:
