networks:
  thingsboard-network:
    external: true
  traefik-network:
    external: true

volumes:
  thingsboard-data:
    external: true
  thingsboard-logs:
    external: true
  thingsboard-kafka:
    external: true

services:
  thingsboard:
    restart: always
    image: ${THINGSBOARD_IMAGE_TAG}
    container_name: thingsboard
    depends_on:
      - kafka
    ports:
      # HTTP port 9090
      # - "8080:9090"
      # MQTT port 1883
      - "18883:1883"
      # Edge RPC port 7070
      - "7070:7070"
      # COAP and LwM2M ports
      - "5683-5688:5683-5688/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thingsboard.rule=Host(`${THINGSBOARD_HOSTNAME}`)"
      - "traefik.http.routers.thingsboard.service=thingsboard"
      - "traefik.http.routers.thingsboard.entrypoints=websecure"
      - "traefik.http.services.thingsboard.loadbalancer.server.port=9090"
      - "traefik.http.routers.thingsboard.tls=true"
      - "traefik.http.routers.thingsboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.thingsboard.loadbalancer.passhostheader=true"
      - "traefik.docker.network=traefik-network"
    environment:
      TB_QUEUE_TYPE: ${TB_QUEUE_TYPE}
      TB_KAFKA_SERVERS: ${TB_KAFKA_SERVERS}
    volumes:
      - thingsboard-data:/data
      - thingsboard-logs:/var/log/thingsboard
    networks:
      - thingsboard-network
      - traefik-network

  kafka:
    restart: always
    image: ${THINGSBOARD_KAFKA_IMAGE_TAG} 
    container_name: thingsboard-kafka
    ports:
      - 9092:9092 #to localhost:9092 from host machine
      - 9093 #for Kraft
      - 9094 #to kafka:9094 from within Docker network
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "OUTSIDE://:9092,CONTROLLER://:9093,INSIDE://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "OUTSIDE://localhost:9092,INSIDE://kafka:9094"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INSIDE"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker" #KRaft
      KAFKA_CFG_NODE_ID: "0" #KRaft
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER" #KRaft
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093" #KRaft
    volumes:
      - thingsboard-kafka:/bitnami
    networks:
      - thingsboard-network