networks:
  node-red-netWwork:
    external: true
  traefik-network:
    external: true

volumes:
  node-red-data:
    external: true

services:
  node-red:
    image: ${NODE_RED_IMAGE_TAG}
    container_name: node-red
    restart: unless-stopped
    environment:
      - TZ=${NODE_RED_TIMEZONE}
    ports:
      # WebUI
      # - "1880:1880"
      # Modbus
      - "10502-10509:10502-10509/TCP"
    networks:
      - node-red-netWwork
      - traefik-network
    labels:

      - "traefik.enable=true"
      - "traefik.http.routers.node-red.rule=Host(`${NODE_RED_HOSTNAME}`)"
      - "traefik.http.routers.node-red.service=node-red"
      - "traefik.http.routers.node-red.entrypoints=websecure"
      - "traefik.http.services.node-red.loadbalancer.server.port=1880"
      - "traefik.http.routers.node-red.tls=true"
      - "traefik.http.routers.node-red.tls.certresolver=letsencrypt"
      - "traefik.http.services.node-red.loadbalancer.passhostheader=true"
      - "traefik.docker.network=traefik-network"
      # Portainer Developer Team Access
      - "io.portainer.accesscontrol.teams=dev,prod"
      - "io.portainer.accesscontrol.users=dev-user"
    # /dev/tty* Device Access
    group_add:
      - dialout
    volumes:
      - node-red-data:/data